version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app # 경로
    overwrite: true
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
